### ISSUE TITLE
Warning in <TH2D::Sumw2> running the plotter with this analyzer

### ISSUE THREAD

**Issue by andresib** [BSM3G/Analyzer#13]
If this version of the Analyzer is used. After running the plotter you will get something like this:

Warning in <TH2D::Sumw2>: Sum of squares of weights structure already created
Warning in <TH2D::Sumw2>: Sum of squares of weights structure already created
Warning in <TH2D::Sumw2>: Sum of squares of weights structure already created

The plotter is functioning ... but just to let you know.

Thanks.

**Comment by padeken** [comment]
This will not change the results. I will remove the warning but I think leave the Sumw2 call in.

**Comment by padeken** [comment]
Done
