### ISSUE TITLE
VBF requirement is not fulfilled anymore

### ISSUE THREAD

**Issue by andresib** [BSM3G/Analyzer#14]
Apparently the code is making matching, but now the VBF requirement is not fulfilled anymore, so if I apply VBF selection, I always get zero, no matter what I do.

For example with a previous version, that was the output for a small ttbar sample:

Conditions 0bjet, high mT

Run Time (cpu): 16.370 s
Time per 1k Events: 0.172 s
Events/s: 5831.216 1/s
                        Name                  Indiv.            Cumulative
---------------------------------------------------------------------------
                 NRecoVertex         95457  ( 1.000)        95457  ( 1.000)
              NRecoTriggers1         95457  ( 1.000)        95457  ( 1.000)
                  NRecoMuon1           218  ( 0.002)          218  ( 0.002)
                  NRecoMuon2           217  ( 0.002)          217  ( 0.002)
              NRecoElectron1         82999  ( 0.869)          180  ( 0.002)
              NRecoElectron2         82999  ( 0.869)          180  ( 0.002)
                   NRecoTau1         92542  ( 0.969)          175  ( 0.002)
                   NRecoTau2         92542  ( 0.969)          175  ( 0.002)
                      METCut           428  ( 0.004)            4  ( 0.000)
                   NRecoBJet         25605  ( 0.268)            1  ( 0.000)
          NDiJetCombinations          **1224**  ( 0.013)            0  ( 0.000)
---------------------------------------------------------------------------

The final yield is zero, but if you applied VBF individually... you get:  1224.

With the new version of the code, the output is:

Selection Efficiency
Total events: 95457

Run Time (real): 22.329 s
Time per 1k Events (real): 0.235 s
Events/s: 4274.964 1/s (real)
                        Name                  Indiv.            Cumulative
---------------------------------------------------------------------------
                 NRecoVertex         95457  ( 1.000)        95457  ( 1.000)
              NRecoTriggers1         95457  ( 1.000)        95457  ( 1.000)
                  NRecoMuon1           218  ( 0.002)          218  ( 0.002)
                  NRecoMuon2           217  ( 0.002)          217  ( 0.002)
              NRecoElectron1         82999  ( 0.869)          180  ( 0.002)
              NRecoElectron2         82999  ( 0.869)          180  ( 0.002)
                   NRecoTau1         **89873**  ( 0.942)          **172**  ( 0.002)
                   NRecoTau2         **89873**  ( 0.942)          **172**  ( 0.002)
                      METCut           428  ( 0.004)            4  ( 0.000)
                   NRecoBJet         25801  ( 0.270)            1  ( 0.000)
          NDiJetCombinations             **0**  ( 0.000)            0  ( 0.000)
---------------------------------------------------------------------------
Apart from the differences in the tau reconstruction (as you can see in bold). Now the event yield if VBF is applied individually is zero.

To support my point I ran over the entire ttbar sample, and the result is the following:

Process     TTbar
   
NRecoVertex     29832735.9 ± 29832735.9   
NRecoTriggers1     29832735.9 ± 29832735.9
NRecoMuon1     65736.0 ± 159.9
NRecoMuon2     65181.1 ± 159.3
NRecoElectron1     55666.8 ± 147.2
NRecoTau1     52771.9 ± 143.3
METCut     1255.7 ± 22.1
NRecoBJet     339.7 ± 11.5
NDiJetCombinations     0.0 ± 0.0

With the old version I was getting:   NDiJetCombinations    13.3 ± 2.0

So, that is a new issue..

**Comment by padeken** [comment]
So tau and Dijet changed ok, will look into this.

**Comment by padeken** [comment]
Can you tell me the commit your "old version" is?
git log
first entry

**Comment by andresib** [comment]
Yes

[andresib@cmslpc41 Analyzer]$ git log
commit b80ff6814f6824acb9b166c4311759927fe6b3ed
Author: Dylan Teague <dylan.o.teague@vanderbilt.edu>
Date:   Fri Jun 30 09:39:09 2017 -0500

    fixed control region issue (for priyanka)

commit 5ffa1045f7ddec8d134ea1f8e2ac80ba26f88a67
Merge: 2ea8984 6dbdf33
Author: Dylan Teague <dylan.o.teague@vanderbilt.edu>
Date:   Sat Jun 10 09:55:46 2017 -0500

    Merge pull request #6 from BSM3G/BTagScaling
    
    B tag scaling

commit 6dbdf33fc35cdfa283c75dc48ca327b0886c36dd
Merge: c7a51e4 2ea8984
Author: Dylan Teague <dylan.o.teague@vanderbilt.edu>
Date:   Sat Jun 10 09:55:32 2017 -0500

    Merge branch 'master' into BTagScaling

commit 2ea89848cf2830f2bd3046719a937c49fc51f567
Merge: 91c0bd3 d68bac3
Author: Dylan Teague <dylan.o.teague@vanderbilt.edu>
Date:   Fri Jun 9 09:03:55 2017 -0500

    fixed merge issues

**Comment by padeken** [comment]
Ok found one problem but looking into the taus

**Comment by padeken** [comment]
For the dijet can you test the current master:
git pull

**Comment by andresib** [comment]
Thanks..
It seems that now it is working

Selection Efficiency 
Total events: 95457

Run Time (real): 22.472 s
Time per 1k Events (real): 0.237 s
Events/s: 4247.813 1/s (real) 
                        Name                  Indiv.            Cumulative
---------------------------------------------------------------------------
                 NRecoVertex         95457  ( 1.000)        95457  ( 1.000) 
              NRecoTriggers1         95457  ( 1.000)        95457  ( 1.000) 
                  NRecoMuon1           218  ( 0.002)          218  ( 0.002) 
                  NRecoMuon2           217  ( 0.002)          217  ( 0.002) 
              NRecoElectron1         82999  ( 0.869)          180  ( 0.002) 
              NRecoElectron2         82999  ( 0.869)          180  ( 0.002) 
                   NRecoTau1         89873  ( 0.942)          172  ( 0.002) 
                   NRecoTau2         89873  ( 0.942)          172  ( 0.002) 
                      METCut           428  ( 0.004)            4  ( 0.000) 
                   NRecoBJet         25801  ( 0.270)            1  ( 0.000) 
          NDiJetCombinations          1222  ( 0.013)            0  ( 0.000) 
---------------------------------------------------------------------------

**Comment by padeken** [comment]
I found the remaining bug. So the dijet did not do the correct thing and I found one issue which has to be changed in the config

DiscrByProngType 1or2or3hps
-->
DiscrByProngType true
ProngType 1or2or3hps

Sorry about that but this is needed in order to maintain the code logic of:
bool for cut
value for cut

And please add in the Run_info.in

UsePileUpWeight 1

So the concussion is use the script
python scripts/have_all_vals.py
because new values will not let the code crash (yeah), but they will be assumed to be false!

The new release is v1.1
https://github.com/BSM3G/Analyzer/releases/tag/v1.1

And with respect to the Leonardos version (30 Jun) no change in event yeld.

But lots of improvements in the code
