### ISSUE TITLE
Problem with DYJetsToLL_M-50_HT-0To70 sample using Zboost option

### ISSUE THREAD

**Issue by andresib** [BSM3G/Analyzer#20]
I'm seeing an strange behaviour applying the Zboost option to the DYJetsToLL_M-50_HT-0To70 sample (the problem is juts with that sample).

Running locally, I do not have any issue:

Run Time (real): 12.891 s
Time per 1k Events (real): 0.119 s
Events/s: 8383.339 1/s (real)
                        Name                  Indiv.            Cumulative
---------------------------------------------------------------------------
                 NRecoVertex        108069  ( 1.000)       108069  ( 1.000)
              NRecoTriggers1        108069  ( 1.000)       108069  ( 1.000)
                  NRecoMuon1         21086  ( 0.195)        21086  ( 0.195)
                  NRecoMuon2         17234  ( 0.159)        17234  ( 0.159)
              NRecoElectron1         85137  ( 0.788)        17057  ( 0.158)
              NRecoElectron2         85137  ( 0.788)        17057  ( 0.158)
                   NRecoTau1        103566  ( 0.958)        16691  ( 0.154)
                   NRecoTau2        103566  ( 0.958)        16691  ( 0.154)
                      METCut             0  ( 0.000)            0  ( 0.000)
                   NRecoBJet        107022  ( 0.990)            0  ( 0.000)
          NDiJetCombinations        108065  ( 1.000)            0  ( 0.000)
---------------------------------------------------------------------------

But when I'm running using the Analyze_Grid in Condor, all the jobs are failing:

This is the output for the same file:

condor_out_1_1624239.stder:
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
/storage/local/data1/condor/execute/dir_3853532/condor_exec.exe: line 42: 3853647 Aborted                 ./Analyzer $infilename $outfilename
xrdcp: No such file or directory processing /storage/local/data1/condor/execute/dir_3853532/Output.2.root
rm: cannot remove `*root': No such file or directory

condor_out_1_1624239.stdout:

Wed Sep 13 09:09:15 CDT 2017
Analyser: Inputfilelist root://cmseos.fnal.gov//store/user/ra2tau/jan2017tuple/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/DYJetsToLL_M-50_HT-0To70_ext1-v2_RunIISummer16MiniAODv2/170207_151723/0000/OutTree_10.root
Analyser: Outputfile Output.2.root
setup start
TOTAL EVENTS: 108069
WJets not needed. They will be deactivated!
Cuts being filled:
eGW   eGZ   eRCenJet   eRJet2   eMET   eRJet1   eSusyCom   eRMuon2   eRBJet   eRMuon1   eRTau1   eRTau2   eRElec1   eMuon1Elec1   eRElec2   eR1stJet   eRTrig1   eR2ndJet   eDiJet   eDiMuon   eDiTau   eMuon1Tau1   eRVertex   eGen
setup complete

0 Events analyzed 0% done
1 Events analyzed 0.00% done
2 Events analyzed 0.00% done
3 Events analyzed 0.00% done

I kindly ask you if you have any idea about this issue.

Thanks,

Regards, Leonardo.

**Comment by andresib** [comment]
I'm sorry, I made a mistake. I'm not able to run locally also:

./Analyzer root://cmseos.fnal.gov//store/user/ra2tau/jan2017tuple/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/DYJetsToLL_M-50_HT-0To70_ext1-v2_RunIISummer16MiniAODv2/170207_151723/0000/OutTree_10.root dyjets.root

The output is:

Analyser: Inputfilelist root://cmseos.fnal.gov//store/user/ra2tau/jan2017tuple/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/DYJetsToLL_M-50_HT-0To70_ext1-v2_RunIISummer16MiniAODv2/170207_151723/0000/OutTree_10.root
Analyser: Outputfile dyjets.root
setup start
TOTAL EVENTS: 108069
WJets not needed. They will be deactivated!
Cuts being filled:
eGW   eGZ   eRCenJet   eRJet2   eMET   eRJet1   eSusyCom   eRMuon2   eRBJet   eRMuon1   eRTau1   eRTau2   eRElec1   eMuon1Elec1   eRElec2   eR1stJet   eRTrig1   eR2ndJet   eDiJet   eDiMuon   eDiTau   eMuon1Tau1   eRVertex   eGen  
setup complete

0 Events analyzed 0% done
1 Events analyzed 0.00% done
2 Events analyzed 0.00% done
3 Events analyzed 0.00% done
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Abort

So the problem is when the ApplyZBoostSF is set as true.

Thanks,

Regards, Leonardo.

**Comment by padeken** [comment]
This is resolved. The problem was a wrong detection of data or mc
